export default class ctegorias {
    static dados = {
        categorias:[
            {
                icone:'',
                descricao:'Todas',
                tag:'todas',
            },
            {
                icone:'',
                descricao:'Academias',
                tag:'academia',
            },
			{
                icone:'',
                descricao:'Açougues',
                tag:'acougues',
            },
			{
                icone:'',
                descricao:'Advocacia',
                tag:'advocacia',
            },
			{
                icone:'',
                descricao:'Arquiteto',
                tag:'arquiteto',
            },
			{
                icone:'',
                descricao:'Assistência Técnica',
                tag:'assistencia_tecnica',
            },
			{
                icone:'',
                descricao:'Auto Elétrica',
                tag:'auto_eletrica',
            },
			{
                icone:'',
                descricao:'Auto Peças',
                tag:'auto_pecas',
            },
			{
                icone:'',
                descricao:'Bares',
                tag:'bares',
            },
			{
                icone:'',
                descricao:'Borracharias',
                tag:'borracharias',
            },
			{
                icone:'',
                descricao:'Cartório',
                tag:'cartorio',
            },
			{
                icone:'',
                descricao:'Cerâmica',
                tag:'ceramica',
            },
			{
                icone:'',
                descricao:'Churrascarias',
                tag:'churrascarias',
            },
			{
                icone:'',
                descricao:'Clínicas Médicas',
                tag:'clinicas_medicas',
            },
			{
                icone:'',
                descricao:'Comunicação Visual',
                tag:'comunicacao_visual',
            },
			{
                icone:'',
                descricao:'Concessionárias',
                tag:'concessionarias',
            },
			{
                icone:'',
                descricao:'Construção',
                tag:'construcao',
            },
			{
                icone:'',
                descricao:'Copiadoras',
                tag:'copiadoras',
            },
			{
                icone:'',
                descricao:'Docerias',
                tag:'docerias',
            },
			{
                icone:'',
                descricao:'Eletrônicas',
                tag:'eletronicas',
            },
			{
                icone:'',
                descricao:'Escolas',
                tag:'escolas',
            },
			{
                icone:'',
                descricao:'Escritórios de Contabilidade',
                tag:'escritorios_de_contabilidade',
            },
			{
                icone:'',
                descricao:'Farmácias',
                tag:'farmacias',
            },
			{
                icone:'',
                descricao:'Festas e Eventos',
                tag:'festas_e_eventos',
            },
			{
                icone:'',
                descricao:'Fotografias',
                tag:'fotografias',
            },
			{
                icone:'',
                descricao:'Funerárias',
                tag:'funerarias',
            },
			{
                icone:'',
                descricao:'Gás',
                tag:'gas',
            },
			{
                icone:'',
                descricao:'Gesso',
                tag:'gesso',
            },
			{
                icone:'',
                descricao:'Horti-Fruti',
                tag:'horti_fruti',
            },
			{
                icone:'',
                descricao:'Hotéis e Pousadas',
                tag:'hoteis_e_pousadas',
            },
			{
                icone:'',
                descricao:'Informática',
                tag:'informatica',
            },
			{
                icone:'',
                descricao:'Internet',
                tag:'internet',
            },
			{
                icone:'',
                descricao:'Laboratórios',
                tag:'laboratorios',
            },
			{
                icone:'',
                descricao:'Lanches',
                tag:'lanches',
            },
			{
                icone:'',
                descricao:'Livrarias',
                tag:'livrarias',
            },
            {
                icone:'',
                descricao:'Lojas',
                tag:'loja',
            },
			{
                icone:'',
                descricao:'Marmitarias',
                tag:'marmitarias',
            },
			{
                icone:'',
                descricao:'Metalúrgica',
                tag:'metalugicas',
            },
			{
                icone:'',
                descricao:'Móteis',
                tag:'moteis',
            },
			{
                icone:'',
                descricao:'Moto-Táxis',
                tag:'moto_taxis',
            },
			{
                icone:'',
                descricao:'Móveis e Eletros',
                tag:'moveis_e_eletros',
            },
			{
                icone:'',
                descricao:'Oficinas',
                tag:'oficinas',
            },
            {
                icone:'',
                descricao:'Óticas',
                tag:'oticas',
            },
            {
                icone:'',
                descricao:'Padarias',
                tag:'padarias',
            },
			{
                icone:'',
                descricao:'Papelaria',
                tag:'papelarias',
            },
            {
                icone:'',
                descricao:'Perfumes e Cosméticos',
                tag:'perfumes_e_cosmeticos',
            },
            {
                icone:'',
                descricao:'Pizzarias',
                tag:'pizzarias',
            },
            {
                icone:'',
                descricao:'Postos',
                tag:'postos',
            },
			{
                icone:'',
                descricao:'Produtos Naturais',
                tag:'produtos_naturais',
            },
            {
                icone:'',
                descricao:'Publicidade',
                tag:'publicidade',
            },
            {
                icone:'',
                descricao:'Queijarias',
                tag:'queijarias',
            },
            {
                icone:'',
                descricao:'Rádios',
                tag:'radios',
            },
            {
                icone:'',
                descricao:'Restaurantes',
                tag:'restaurantes',
            },
			{
                icone:'',
                descricao:'Salão de Beleza',
                tag:'salao_de_beleza',
            },
			{
                icone:'',
                descricao:'Serviços',
                tag:'servicos',
            },
			{
                icone:'',
                descricao:'Sorveteria',
                tag:'sorveteria',
            },
			{
                icone:'',
                descricao:'Supermercados',
                tag:'supermercados',
            },
			{
                icone:'',
                descricao:'Táxi',
                tag:'taxi',
            },
			{
                icone:'',
                descricao:'Telefones Úteis',
                tag:'telefones_uteis',
            },
			{
                icone:'',
                descricao:'Transportes',
                tag:'transportes',
            },
			{
                icone:'',
                descricao:'Variedades',
                tag:'variedades',
            }
        ]
    }
}
