export default class empresas {

    static dados = {
        empresas: [
        	{
        		nome: 'Rede Fácil Construir',
        		categoria: 'construcao',
        		logo: require('eGuia/src/imagens/logos/a.png'),
        		descricao: 'Hidráulicos, Ferragens, Elétricos, Tintas, Madeiras, Cimentos, Telhas, Tijolos, Pisos e Etc.',
        		endereco: 'Rua Juvenal Lamartine, 83, Centro',
        		funcionamento: 'Funcionamento de segunda a sexta de 7h às 18h',
        		organizacao: 'Org.: Erivan',
        		entrega: 'Entrega em domicílio.',
        		telefones: ['(84) 9 9436-2000', '(84) 3473-2224'],
        		emails: [''],
        		cartoes: ['master', 'visa', 'hiper', 'construcard Caixa'],
                coords: ['-6.411657', '-36.790560'],
                corDeFundo: 'white',
        	},
            {
        		nome: 'Pizzas Novo Sabor',
        		categoria: 'pizzarias',
        		logo: require('eGuia/src/imagens/logos/b.png'),
        		descricao: 'Venha Saborear a melhor pizza da cidade.',
        		endereco: 'Rua. Pedro Vital, 85, Novo Horizonte',
        		funcionamento: 'Funcionamos de Sexta-Feira à Terça-Feira.',
        		organizacao: 'Org.: Inácio Júnior & Família',
        		entrega: 'Entrega em Domicílio.',
        		telefones: ['(84) 9 9434-0827'],
        		emails: ['empresabacademia@mail.com'],
        		cartoes: ['master', 'visa'],
                coords: ['-6.412619', '-36.785118'],
                corDeFundo: 'white',
        	},
            {
        		nome: 'Óticas Marques',
        		categoria: 'oticas',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Sua Visão com Qualidade',
        		endereco: 'Av. Sílvio Bezerra de Melo, 220, Centro',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Amaury Torquato de Fonseca',
        		entrega: 'Venda apenas no local',
        		telefones: ['(84) 3473-2391'],
        		emails: ['amauritorquato@hotmail.com'],
        		cartoes: ['master', 'visa', 'hiper'],
                coords: ['-6.411990', '-36.787500'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Loja Moto Sat',
        		categoria: 'loja',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Vendas e Instalação em Antenas e Sistema de Segurança.',
        		endereco: 'Rua Francisco Gomes Filho, 151, Centro',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Rogério',
        		entrega: 'Venda apenas no local',
        		telefones: ['(84) 3473-2590', '(84) 9 9160-1790'],
        		emails: [],
        		cartoes: ['master', 'visa'],
                coords: ['-6.4117421','-36.7884978'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Medeiros Construção',
        		categoria: 'construcao',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Construir é aqui! Material de Construção,  Elétrircos, Hidráulicos, Tintas e Acessórios em Geral.',
        		endereco: 'Rua Geraldo Lopes de Araújo, 83, Centro',
        		funcionamento: 'Funcionamos de Segunda à Sábado.',
        		organizacao: 'Org.: Zé Louro e Filhos',
        		entrega: 'Venda apenas no local',
        		telefones: ['(84) 3473-2123', '(84) 9 9474-7044'],
        		emails: [],
        		cartoes: ['master', 'visa','hiper','diners', 'caixa'],
                coords: ['-6.4117421','-36.7884978'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Lanchonete e Pizzaria do Jorge',
        		categoria: 'lanches',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Aqui você conhece, você confia.',
        		endereco: 'Rua Emílio Vale, 37, Centro',
        		funcionamento: 'Funcionamos de Quarta à Sábado.',
        		organizacao: 'Org.: Jorge e Família',
        		entrega: 'Vendas à domicílio e no local',
        		telefones: ['(84) 9 9160-1334'],
        		emails: [],
        		cartoes: ['não aceitamos cartões'],
                coords: ['-6.411661', '-36.789290'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Vetericampo',
        		categoria: 'loja',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Saúde para o campo!',
        		endereco: 'Rua Juvenal Lamartine, 03, Centro',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Adriano Góes',
        		entrega: 'Entregamos em Domicílio',
        		telefones: ['(84) 3473-2424'],
        		emails: [],
        		cartoes: ['master', 'visa','hiper'],
                coords: ['-6.411075', '-36.790966'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Edival Ciclimotopeças',
        		categoria: 'auto_pecas',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Serviços em geral, borracharia, troca de óleo e acessórios!',
        		endereco: 'Nemésio Palmeira, 335, Santo Antônio',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Edival',
        		entrega: 'Venda apenas no local',
        		telefones: ['(84) 3473-2424'],
        		emails: [],
        		cartoes: ['master', 'visa','hiper'],
                coords: ['-6.409906', '-36.782476'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Ethel Moraes - Advocacia',
        		categoria: 'advocacia',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Advocacia',
        		endereco: 'Rua Emílio Vale, Centro',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Ethel Moraes',
        		entrega: '',
        		telefones: ['(84) 9 8111-7111','(84) 9 9910-2088'],
        		emails: ['ethelmoraes@globo.com'],
        		cartoes: ['master', 'visa','hiper'],
                coords: ['-6.411075', '-36.790966'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Árvore de Vida',
        		categoria: 'produtos_naturais',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Integrando Saúde, Beleza e Natureza',
        		endereco: 'Rua Joaquim Lopes Pequeno, 278, Centro',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: João e Cristina',
        		entrega: 'Vendas apenas no local',
        		telefones: ['(84) 9 9414-5272','(84) 9 9160-1660'],
        		emails: [''],
        		cartoes: ['master', 'visa'],
                coords: ['-6.411069', '-36.790512'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Árvore de Vida',
        		categoria: 'produtos_naturais',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Integrando Saúde, Beleza e Natureza',
        		endereco: 'Rua Joaquim Lopes Pequeno, 278, Centro',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: João e Cristina',
        		entrega: 'Vendas apenas no local',
        		telefones: ['(84) 9 9414-5272','(84) 9 9160-1660'],
        		emails: [''],
        		cartoes: ['master', 'visa'],
                coords: ['-6.411069', '-36.790512'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Árvore de Vida',
        		categoria: 'produtos_naturais',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Integrando Saúde, Beleza e Natureza',
        		endereco: 'Rua Joaquim Lopes Pequeno, 278, Centro',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: João e Cristina',
        		entrega: 'Vendas apenas no local',
        		telefones: ['(84) 9 9414-5272','(84) 9 9160-1660'],
        		emails: [''],
        		cartoes: ['master', 'visa'],
                coords: ['-6.411069', '-36.790512'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Clínica Estética Center',
        		categoria: 'clinicas_medicas',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Cuidando bem da sua saúde.',
        		endereco: 'Rua Francisco Gomes Filho, 112, Centro',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Nara Castro e Família',
        		entrega: '',
        		telefones: ['(84) 9 3473-2300','(84) 9 9160-1707'],
        		emails: ['clinicaestaeticacenter@gmail.com'],
        		cartoes: ['master', 'visa'],
                coords: ['-6.411348', '-36.788726'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Flávio Ricardo Fotographer',
        		categoria: 'fotografias',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Há 11 anos apaixonado por imagens.',
        		endereco: 'Rua Joaquim José de Medeiros, 60, Centro',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Flávio Ricardo',
        		entrega: '',
        		telefones: ['(84) 9 9975-4940','(84) 3473-2637'],
        		emails: ['flavioricardorn@gmail.com'],
        		cartoes: ['master', 'visa'],
                coords: ['-6.411964', '-36.790687'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Tok Final',
        		categoria: 'loja',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Confecções Masculina, Feminina, Infantil, Perfumaria e Acessórios.',
        		endereco: 'Rua Juvenal Lamartine, 72, Centro',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Jaqueline Góes',
        		entrega: 'Vendas no local.',
        		telefones: ['(84) 9 3473-2370'],
        		emails: [''],
        		cartoes: ['master', 'visa', 'elo', 'diners'],
                coords: ['-6.411599', '-36.790696'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Consultório Odontológico Dedyce Góes',
        		categoria: 'clinicas_medicas',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Compromisso, Responsabilidade e Atenção com sua saúde e com você.',
        		endereco: 'Rua Antônio Apolináario, Centro',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Dedyce e Família',
        		entrega: '',
        		telefones: ['(84) 9 9455-8104'],
        		emails: [''],
        		cartoes: ['master', 'visa'],
                coords: ['-6.412449', '-36.786631'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Academia Evolution',
        		categoria: 'academia',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Musculação em Geral. A Academia do Léo.',
        		endereco: 'Rua Dr. Drummond, s/n, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Leonardo',
        		entrega: '',
        		telefones: ['(84) 9 9460-6202'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411523', '-36.787555'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Vetericampo',
        		categoria: 'clinicas_medicas',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Saúde para o campo.',
        		endereco: 'Rua Juvenal Lamartine, 03, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Adriano Góes',
        		entrega: 'Entrega em domicílio',
        		telefones: ['(84) 3473-2424'],
        		emails: ['vetericampocruzeta@hotmail.com'],
        		cartoes: ['master', 'visa', 'hiper'],
                coords: ['-6.411080', '-36.790925'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Portal dos Presentes',
        		categoria: 'loja',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Artigos para presentes, armarinho, informática, brinquedos, aviamentos, papelaria e perfumaria.',
        		endereco: 'Praça Celso Azevedo, 67, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Neto e Bel',
        		entrega: '',
        		telefones: ['(84) 9 9160-1401', '(84) 3473-2477'],
        		emails: [''],
        		cartoes: ['master', 'visa', 'hiper'],
                coords: ['-6.412001', '-36.789408'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Marcelo Aquino Arquitetura',
        		categoria: 'arquiteto',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: '',
        		endereco: 'Rua 24 de Outubro, s/n, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Marcelo Aquino',
        		entrega: '',
        		telefones: ['(84) 9 9197-1121'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411342', '-36.790525'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Klézio Cell',
        		categoria: 'assistencia_tecnica',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Assisstência Técnica, Peças e Acessórios para Celulares e Informática.',
        		endereco: 'Rua 24 de Outubro, 155, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Klézio',
        		entrega: '',
        		telefones: ['(84) 9 9984-9433'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411736', '-36.791207'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Duda Auto Elétrica',
        		categoria: 'auto_eletrica',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Peças e Serviços na Parte Elétrica.',
        		endereco: 'Rua José Sagaria de Maria, Bairro: Santo Antônio, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Duda',
        		entrega: '',
        		telefones: ['(84) 9 9453-7965'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.410147', '-36.781412'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'JN - Casa do Bolo',
        		categoria: 'lanches',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Bolos para Aniversários, Casamentos, Variedades de Salgados e Pães Caseiros, etc.',
        		endereco: 'Rua José Sagario de Maria, 50, Santo Antônio, Cruzeta-RN.',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Dedyce e Família',
        		entrega: 'Entrega à domicílio',
        		telefones: ['(84) 9 9451-5233', '(84) 9 9160-7927'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.410456', '-36.781216'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Bar do Leite',
        		categoria: 'bar',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'A qualidade faz a diferença.',
        		endereco: 'Avenida Sílvio Bezerra de Melo, 81, Centro, Cruzeta-RN.',
        		funcionamento: 'Funcionamos de Terça a Domingo.',
        		organizacao: 'Org.: Reginaldo e Família',
        		entrega: '',
        		telefones: ['(84) 9 9130-2194'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411765', '-36.788657'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Lulu Bombons',
        		categoria: 'loja',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Balas, Bombons, Chocolates, Artigos p/ festas, Prod. Descartáveis e etc.',
        		endereco: 'Rua Luiz de França Dantas, 01, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Luciano',
        		entrega: 'Entrega à domicílio',
        		telefones: ['(84) 9 9110-3577', '(84) 3473-2577'],
        		emails: [''],
        		cartoes: ['visa','master', 'hiper'],
                coords: ['-6.411982', '-36.787543'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Seridó Plast',
        		categoria: 'loja',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Acreditamos na força do trabalho. Vendas no Atacado e Varejo.',
        		endereco: 'Rua Juvenal Lamartine, 33, Centro, Cruzeta-RN.',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Edson Filho',
        		entrega: 'Entrega à domicílio',
        		telefones: ['(84) 3473-2071', '(84) 9 9121-2173'],
        		emails: [''],
        		cartoes: ['hiper', 'visa', 'master'],
                coords: ['-6.411198', '-36.790840'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Super Dog',
        		categoria: 'lanches',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'O mais gostoso da cidade.',
        		endereco: 'Avenida Silvio Bezerra de Melo (próximo ao Bar do Leite)',
        		funcionamento: 'Funcionamos de Terça a Domingo.',
        		organizacao: 'Org.: Fogoza & Família',
        		entrega: 'Entrega à domicílio',
        		telefones: ['(84) 9 9165-5504'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411823',  '-36.788489'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Cerâmica Cruzeta',
        		categoria: 'ceramica',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Telhas, tijolos e lajotass de qualidade.',
        		endereco: 'BR 288, KM 04, Zona Rural, Cruzeta-RN.',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Dedé de Mauro e Família',
        		entrega: '',
        		telefones: ['(84) 9 9197-1121'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.415228', '-36.751333'],
                corDeFundo: 'white',
        	},
						{
        		nome: 'Rinaldo Chaves e Serviçoss',
        		categoria: 'assistencia_tecnica',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Chaves e Serviços.',
        		endereco: 'Em frente a Maré Mansa.',
        		funcionamento: 'Funcionamos no Sábado.',
        		organizacao: 'Org.: Rinaldo',
        		entrega: '',
        		telefones: ['(84) 9 9489-6299'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411513', '-36.791020'],
                corDeFundo: 'white',
        	},
						{
        		nome: 'Clínica Castros',
        		categoria: 'clinicas_medicas',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Cuidando bem da sua saúde.',
        		endereco: 'Rua Francisco Gomes Filho, 112, Centro, Cruzeta-RN.',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Dedé de Mauro e Família',
        		entrega: '',
        		telefones: ['(84) 9 9160-1707'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411367', '-36.788691'],
                corDeFundo: 'white',
        	},
						{
        		nome: 'Francinete Variedades',
        		categoria: 'loja',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Todos os estilos em um só lugar.  Roupas, Calçados, Perfumaria, Cama, Mesa, etc.',
        		endereco: 'Rua Cícero Simão Bezerra, 183, Cruzeta-RN.',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Francinete',
        		entrega: '',
        		telefones: ['(84) 3473-2515','(84) 9 9152-0555'],
        		emails: [''],
        		cartoes: ['visa', 'master', 'hiper'],
                coords: ['-6.413715', '-36.783333'],
                corDeFundo: 'white',
        	},
						{
        		nome: 'Jaísa Modas',
        		categoria: 'loja',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: '',
        		endereco: 'Rua Nemésiop Palmeiras, 21, Santo Antônio, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Jaísa',
        		entrega: '',
        		telefones: ['(84) 3473-2341','(84) 9 9409-9660'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411636', '-36.785215'],
                corDeFundo: 'white',
        	},
						{
        		nome: 'Boutique Mary Anne - Estilo e elegância.',
        		categoria: 'ceramica',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Confecções Feminina, Infantil, Acessórios e Calçados.',
        		endereco: 'Rua Juvenal Lamartine, 39, Centro, Cruzeta-RN.',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Aninha e Francisquinha',
        		entrega: '',
        		telefones: ['(84) 3473-2524','(84) 9 9429-3591'],
        		emails: ['m aryeannefaccao@yahoo.com.br'],
        		cartoes: ['visa', 'master', 'hiper'],
                coords: ['-6.411299', '-36.790770'],
                corDeFundo: 'white',
        	},
						{
        		nome: 'Econtec',
        		categoria: 'escritorios_de_contabilidade',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Contabilizando o seu sucesso.',
        		endereco: 'Rua Raimundo Bezerra, 178, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Seilha e Naide',
        		entrega: '',
        		telefones: ['(84) 3473-2048','(84) 9 9197-5717'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411187', '-36.791373'],
                corDeFundo: 'white',
        	},
						{
        		nome: 'Inovasom',
        		categoria: 'variedades',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Som | Palco | Gerador',
        		endereco: 'Rua Nemésio Palmeiras, 21, Santo Antônio, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Hutson',
        		entrega: '',
        		telefones: ['(84) 3473-2341', '(84) 9 9110-3556'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411683', '-36.785282'],
                corDeFundo: 'white',
        	},
						{
        		nome: 'DrogaCenter',
        		categoria: 'farmacias',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Saúde em Primeiro Lugar!',
        		endereco: 'Rua Luiz de França Dantas, 03',
        		funcionamento: 'Funcionamos de Segunda a Domingo.',
        		organizacao: 'Org.: Mário Sérgio',
        		entrega: '',
        		telefones: ['(84) 3473-2522'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411952', '-36.787572'],
                corDeFundo: 'white',
        	},
						{
        		nome: 'Francis Buffet',
        		categoria: 'festas_e_eventos',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Casamentos, Formaturas, Batizados, Aniversários Infantis, etc.',
        		endereco: 'Rua Antônio Sabino de Oliveira, 115, Centro, Cruzeta-RN.',
        		funcionamento: 'Funcionamos de Segunda a Segunda.',
        		organizacao: 'Org.: Francisca e Paulo César',
        		entrega: '',
        		telefones: ['(84) 3473-2204', '(84) 9 9818-0947','(84) 9 9108-1375', ''],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.414285', '-36.791147'],
                corDeFundo: 'white',
        	},
						{
        		nome: 'Uniplan',
        		categoria: 'funerarias',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Assistência Funerária Integrada.',
        		endereco: 'Rua Joaquim Lopes Pequeno, 292, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Carminha',
        		entrega: '',
        		telefones: ['(84) 9 9168-9089'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411005', '-36.790536'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'BigMac Lanches',
        		categoria: 'lanches',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'O sabor que lhe satisfaz!',
        		endereco: 'Praça de Eventos Sílvio  Bezerra de Melo, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Terça a Domingo.',
        		organizacao: 'Org.: Aldo e Cleide',
        		entrega: '',
        		telefones: ['(84) 9 9160-7944'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411982', '-36.788223'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Delírio Modas',
        		categoria: 'loja',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Moda Íntima e Acessórios.',
        		endereco: 'Rua Pedro Vital, 184, Novo Horizonte, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Ana Cristina',
        		entrega: '',
        		telefones: ['(84) 9 9140-7579'],
        		emails: [''],
        		cartoes: ['visa', 'master', 'hiper'],
                coords: ['-6.413446', '-36.784724'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Lya Análises',
        		categoria: 'laboratorios',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Laboratório de Análises Clínicas. Todos os tipos de exames, DNA e Biopsia.',
        		endereco: 'Av. Sílvio Bezerra de Melo, 20, Novo Horizonte, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Lya Guedes',
        		entrega: '',
        		telefones: ['(84) 3473-2469'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411944', '-36.784715'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Serralheria do Jeová',
        		categoria: 'metalugicas',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Solda em domicílio, Portões e Grades. Já entregamos nossos serviços pintados.',
        		endereco: 'Rua Jefferson Medeiros, 300, Novo Horizonte, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Jeová e Família',
        		entrega: '',
        		telefones: ['(84) 9 9479-6983'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.415994', '-36.785217'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Serralheria Araújo',
        		categoria: 'metalugicas',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Portões e Esquadrilhas metálicas, Confecção de Reboques, Estrutura Metálicas e etc.',
        		endereco: 'Av. Carmelita Monteiro, 22, Novo Horizonte, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: José Evaldo.',
        		entrega: '',
        		telefones: ['(84) 9 99410-8266', '(84) 9 9979-8034'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.415693', '-36.784683'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Paulino Motos',
        		categoria: 'auto_pecas',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Peças, Serviços, Acessórios e Mecânica em geral.',
        		endereco: 'Rua Leôncio Pires Galvão, 70, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Sérvulo Paulino Filho',
        		entrega: '',
        		telefones: ['(84) 3473-2033','(84) 9 9100-4642', '(84) 9 9962-7158'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.412059', '-36.791154'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Júnior Motos',
        		categoria: 'auto_pecas',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Peças, Serviços e Acessórios Multi Marcas',
        		endereco: 'Rua José Sebastião de Maria, 48, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Aldo Júnior e Sirlei',
        		entrega: '',
        		telefones: ['(84) 9 9102-5133', '(84) 9 8755-1806'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.413184', '-36.787913'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Moto Sat',
        		categoria: 'moto_taxis',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Ligou, Chegou!',
        		endereco: 'Rua Francisco Gomes, 151, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Rogério',
        		entrega: '',
        		telefones: ['(84) 9 9168-9089'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411551', '-36.788459'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Oficina Mecânica e Metalúrgica SLEP',
        		categoria: 'oficinas',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Fabricamos Portões, Janelas, Oficinas de Solda, Lantenagem, Esquadrilhas e pinturas.',
        		endereco: 'Avenida Carmelita Monteiro da Silva, Novo Horizonte, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Edson Raimundo (Nenem)',
        		entrega: '',
        		telefones: ['(84) 9 9166-1319'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.414882', '-36.783880'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Papelaria Malú',
        		categoria: 'papelarias',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Material p/ escritório, material escolar, xerox, plastificação, encadernação, digitação, envio por e-mail e etc.',
        		endereco: 'Rua Juvenal Lamartine, 62, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Dunga e Marlí',
        		entrega: '',
        		telefones: ['(84) 3473-2316'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411525', '-36.790727'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Lanche e Pizzaria Marques',
        		categoria: 'pizzarias',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Lanches, Pizzaria e Sorveteria.',
        		endereco: 'Rua Bartolomeu Fernandes de Araújo, 17, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Domingo.',
        		organizacao: 'Org.: Fábio e Márcia',
        		entrega: '',
        		telefones: ['(84) 3473-2385', '(84) 9 9151-0794'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.412192', '-36.786350'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Silvia Marmitaria & Quentinhas',
        		categoria: 'marmitarias',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: '',
        		endereco: 'Av. Carmelita Monteiro, 28, Novo Horizonte, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Sílvia',
        		entrega: '',
        		telefones: ['(84) 9 9141-9971'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.416029', '-36.784982'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Rancho Dona Carmelita',
        		categoria: 'restaurantes',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Café da Manhã, Almoço Self-Service',
        		endereco: 'Avenida Carmelita Monteiro, 26, Novo Horizonte, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Domingo.',
        		organizacao: 'Org.: Raybar e Família',
        		entrega: '',
        		telefones: ['(84) 9 9408-6038'],
        		emails: [''],
        		cartoes: ['visa', 'master', 'hiper', 'elo', 'vale', 'sodexo', 'diners'],
                coords: ['-6.415589', '-36.784784'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Visual Victory',
        		categoria: 'salao_de_beleza',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Cortes unissex, Hidratação, Química em geral, Penteados, Maquiagens, Depilação, etc.',
        		endereco: 'Rua Teotônio Guerra, 83, Novo Horizonte, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Domingo.',
        		organizacao: 'Org.: Vitória',
        		entrega: '',
        		telefones: ['(84) 9 9168-9089'],
        		emails: [''],
        		cartoes: ['visa', 'hiper', 'master'],
                coords: ['-6.411005', '-36.790536'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Auto Estima Salão',
        		categoria: 'salao_de_beleza',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Cortes em geral, Depilação, Maquiagens, Manicure, Pedicure decoradas.',
        		endereco: 'Rua José Sagário de Maria, 124, Santo Antônio, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Domingo.',
        		organizacao: 'Org.: Adriana, Anne e Michele',
        		entrega: '',
        		telefones: ['(84) 9 9160-7929', '(84) 9 9193-3597', '(84) 9 9488-8201'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.410574', '-36.781294'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Solana Cabelos',
        		categoria: 'salao_de_beleza',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Cortes Unissex, Química, Escovas, Hidratação, Maquiagem, etc.',
        		endereco: 'Rua Padre José Dantas Cortês, 09, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Domingo.',
        		organizacao: 'Org.: Simone',
        		entrega: '',
        		telefones: ['(84) 9 9199-5535'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.412561', '-36.787313'],
                corDeFundo: 'white',
        	},
			{
        		nome: 'Loja Moto Sat',
        		categoria: 'loja',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Assistência Funerária Integrada.',
        		endereco: 'Rua Francisco Gomes, 151, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Domingo.',
        		organizacao: 'Org.: Rogério',
        		entrega: '',
        		telefones: ['(84) 3473-2590', '(84) 9 9160-1790'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411551', '-36.788459'],
                corDeFundo: 'white',
        	},
									{
        		nome: 'Mercadinho Bom Preço',
        		categoria: 'supermercados',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Estivas, Cereais, Frios, Bebidas, Açougue, Prod. p/ Limpeza e etc.',
        		endereco: 'Rua Joaquim Lopes Pequeno, 292, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Domingo a Domingo.',
        		organizacao: 'Org.: Patrício e Família',
        		entrega: 'Entregamos à domicílio',
        		telefones: ['(84) 3473-2320', '(84) 9 9214-2290'],
        		emails: [''],
        		cartoes: ['visa', 'master', 'hiper', 'diners'],
                coords: ['-6.411967', '-36.787790'],
                corDeFundo: 'white',
        	},
												{
        		nome: 'Sacolão da Ecônomia',
        		categoria: 'supermercados',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Preço baixo só aqui.',
        		endereco: 'Rua Juvenal Lamartine, 23, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Itamires Galvão',
        		entrega: 'Entregamos à domicílio',
        		telefones: ['(84) 3473-2260', '(84) 9 9195-5507'],
        		emails: [''],
        		cartoes: [],
                coords: ['-6.411253', '-36.790830'],
                corDeFundo: 'white',
        	},
												{
        		nome: 'Rede Seridó - Supermercado Popular',
        		categoria: 'supermercados',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: '',
        		endereco: 'Rua Tibúrtino Bezerra, 224, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Dudú',
        		entrega: 'Entregamos à domicílio',
        		telefones: ['(84) 3473-2346'],
        		emails: ['supopopular@redeserido.com.br'],
        		cartoes: ['visa', 'master', 'hiper', 'sodexo'],
                coords: ['-6.411967', '-36.787790'],
                corDeFundo: 'white',
        	},
												{
        		nome: 'Avistão',
        		categoria: 'supermercados',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Sua nova opção em comprar barato! vendas no atacado e varejo.',
        		endereco: 'Avenida Sílvio Bezerra de Melo, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Léo e Rayslânia',
        		entrega: 'Entregamos à domicílio',
        		telefones: ['(84) 9 9168-0264'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411976', '-36.785840'],
                corDeFundo: 'white',
        	},
												{
        		nome: 'Supermercado Nossa Senhora dos Remédios',
        		categoria: 'supermercados',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Completo Sortimento de Cereais e Auto Atendimento.',
        		endereco: 'Rua Raimundo Bezerra, 150, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Milton & Stefânia',
        		entrega: 'Entregamos à domicílio',
        		telefones: ['(84) 3473-2318'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.411051', '-36.791093'],
                corDeFundo: 'white',
        	},
												{
        		nome: 'Supermercado Santa Edwirges',
        		categoria: 'supermercados',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'A sua ecônomia começa aqui.',
        		endereco: 'Av. Dr. Sílvio Bezerra de Melo, 253, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Domingo.',
        		organizacao: 'Org.: Pequeno e Mara',
        		entrega: 'Entregamos à domicílio',
        		telefones: ['(84) 3473-2357', '(84) 9 9405-0537'],
        		emails: [''],
        		cartoes: ['visa', 'master', 'hiper'],
                coords: ['-6.411854', '-36.786204'],
                corDeFundo: 'white',
        	},
												{
        		nome: 'Oficina Silva - O seu serviço é aqui!',
        		categoria: 'oficinas',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Serviço de torno e solda, engates p/ motos, carrocinhas, portões, andaimes e peças p/ cerâmica.',
        		endereco: 'Rua Francisco Raimundo de Araújo, 53, Centro, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Domingo.',
        		organizacao: 'Org.: Raimundo da Silva',
        		entrega: 'Entregamos à domicílio',
        		telefones: ['(84) 3473-2320', '(84) 9 9214-2290'],
        		emails: [''],
        		cartoes: ['visa', 'master', 'hiper', 'diners'],
                coords: ['-6.414192', '-36.792679'],
                corDeFundo: 'white',
        	},
												{
        		nome: 'Oficina Campos',
        		categoria: 'oficinas',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'O máximo em manutenção eletromecânica. Oficina de tornearia, manutenção em moto bombas, rebobinamento em motores elétricos e máquinas de solda, etc.',
        		endereco: 'Rua Pedro Vital, 199, Novo Horizonte, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: José Juvenito Campos, Sidney Campos, Máximo Campos',
        		entrega: '',
        		telefones: ['(84) 3473-2262', '(84) 9 9156-1636'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.413455', '-36.784673'],
                corDeFundo: 'white',
        	},
															{
        		nome: 'Cruzeta Moto Car',
        		categoria: 'oficinas',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Compra, Venda e Troca',
        		endereco: 'Rod. RN 288, Cruzeta-RN',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Alberlândio e Alex',
        		entrega: '',
        		telefones: ['(84) 9 9189-4998', '(84) 9 9694-0609'],
        		emails: [''],
        		cartoes: [''],
                coords: ['-6.414346', '-36.792764'],
                corDeFundo: 'white',
        	},
															{
        		nome: 'Amilson Viagens',
        		categoria: 'oficinas',
        		logo: require('eGuia/src/imagens/logos/c.png'),
        		descricao: 'Conforto e Segurança - Cruzeta a Caicó diariamente',
        		endereco: '',
        		funcionamento: 'Funcionamos de Segunda a Sábado.',
        		organizacao: 'Org.: Amilson',
        		entrega: '',
        		telefones: ['(84) 9 9186-3334'],
        		emails: [''],
        		cartoes: [''],
                coords: [''],
                corDeFundo: 'white',
        	},
            {
                nome: '',
            	categoria: 'todas',
        		logo: require('eGuia/src/imagens/bloco.png'),
                logoMin: require('eGuia/src/imagens/bloco.png'),
        	},
        ]
    }
}
